### PR TITLE
feat: add french translations

### PR DESCRIPTION
**Pull request by tbrunain**
Hello,

I added a first version for the french localization !

### CODE REVIEW

**Comment by kanatliemre** [comment]
Hello,

Thank you for taking the time and doing this! I don't want to merge this request yet because we actually have a new version of the wallet coming very soon. It will require an update with the new language.

**Comment by tbrunain** [comment]
Sure ! I'll wait and do the same on the new version then :)

**Comment by kanatliemre** [comment]
@tbrunain The new version is released but don't do translations yet because localization is incomplete. I'll leave a comment here once the project is ready for localization. Thanks in advance!

**Comment by tbrunain** [comment]
Ok noted : ) new version look really nice btw ;)

**Comment by kanatliemre** [comment]
@tbrunain Hello! Coming a bit late but we are doing the translations again, feel free to join in at: https://crwd.in/walletavaxnetwork

All you have to do is sign in, select a language and get started.

**Pull request closed without merging**
